server:
  domain: follow
  version: 1.0
  jwtSecret: 38324
  grpcAddress: "127.0.0.1:10003"

mysql:
  driverName: mysql
  host: 10.151.1.122
  port: 3306
  database: grpc_todo_list
  username: root
  password: 123456
  charset: utf8mb4

etcd:
  address: 10.151.1.122:12379

redis:
  address: 10.151.1.122:6379
  password:


rabbitmq:
  rabbitMQ: amqp
  rabbitMQUser: guest
  rabbitMQPassWord: guest
  rabbitMQHost: 10.151.1.122
  rabbitMQPort: 5672
